### ISSUE TITLE
这是什么情况？nodejs 16.16

### ISSUE THREAD

**Issue by woliven** [CyrusZhou-CN/MP_WeiXin_ChatGPT#4]
![image](https://github.com/CyrusZhou-CN/MP_WeiXin_ChatGPT/assets/64478416/6bf1e21b-e40e-4c2e-8d15-bef3dd0e3b99)
![image](https://github.com/CyrusZhou-CN/MP_WeiXin_ChatGPT/assets/64478416/ec61c056-6193-4162-a9e0-d34cd452958f)

**Comment by CyrusZhou-CN** [comment]
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1041-azure x86_64)
nodejs 16.16   npm 8.11.0  next 13.4.12
测试成功
npm install next --save
npm cache clean --force
npm run dev
试一下
